version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bike-rent
      MYSQL_USER: avnadmin
      MYSQL_PASSWORD: garek123
    ports:
      - "3306:3306"
    volumes:
      - ./init_utf8.sql:/docker-entrypoint-initdb.d/init_utf8.sql
